### PR TITLE
FH-3002 - update cluster cloud template

### PR DESCRIPTION
**Pull request by wtrocki**
## Motivation

- Update cloud-cluster example to be aligned with non clustered one
- Verify if clustering work and nodes are properly killed.
- Updated versions of the most essential packages.

### CODE REVIEW

**Comment by david-martin** [comment]
@wtrocki  I tried this out (with some additional logs) and can see the following
```
MASTER: numCPUs=4
amqp connected
startWorker cluster.worker.id=1
App started at: Tue Jan 17 2017 10:58:37 GMT+0000 (UTC) on port: 8181
startWorker cluster.worker.id=2
startWorker cluster.worker.id=3
App started at: Tue Jan 17 2017 10:58:37 GMT+0000 (UTC) on port: 8181
App started at: Tue Jan 17 2017 10:58:37 GMT+0000 (UTC) on port: 8181
amqp connected
startWorker cluster.worker.id=4
App started at: Tue Jan 17 2017 10:58:37 GMT+0000 (UTC) on port: 8181
amqp connected
amqp connected
amqp connected
```

I think this Environment has only 1 CPU assigned to the dyno (i'll need to verify), not 4.
If that is the case, we'll need to determine how many CPUs are actually available in the linux container, and only fork that many times.

Alternatively, if we can't reliably determine, a developer would have to know in advance and hardcode (or better yet, set an env var) with the number of CPUs that is known to be in an Environment

**Comment by david-martin** [comment]
@wtrocki Using `nproc`, we can determine the actual number of CPU's available to the process in a dyno.

This function shells out to `nproc` to determine the number of CPUs.
We verified this in a multi CPU dyno too.
```javascript
function getNumCPUs(cb) {
  var numCPUs = process.env.FH_NUM_WORKERS;
  if (!numCPUs) {
      require('child_process').exec('nproc', function(err, stdout){
        if (err) return cb(err);
        return cb(null, parseInt(stdout));
      });
  }
  process.nextTick(function() {
      return cb(null, numCPUs);
  });
}


function start() {
  if (cluster.isMaster) {
    var numCPUs = getNumCPUs(function(err, numCPUs) {
        if (err) {
            console.error(err);
            process.exit(1);
        }
        console.log('MASTER: numCPUs=' + numCPUs);
        for (var i = 0; i < numCPUs; i++) {
            var worker = cluster.fork();
            workers.push(worker);
        }

        // Handle workers exiting
        cluster.on('exit', workerExitHandler);
    });
  } else {
    startWorker();
  }
}
```

Log output when using ab
```
MASTER: numCPUs=undefined
MASTER: numCPUs=1
amqp connected
startWorker cluster.worker.id=1
App started at: Tue Jan 17 2017 11:40:14 GMT+0000 (UTC) on port: 8181
amqp connected
```

I'll update this PR with above changes for re-review

**Comment by david-martin** [comment]
@wtrocki I've pushed https://github.com/feedhenry-templates/helloworld-cloud-cluster/pull/51/commits/9c4ddbcd6a1cb0069451c610bf9eeb8c48e8f4f9 to use `nproc` to get the number of cpus.
If you could review?

**Comment by jasonmadigan** [comment]
@david-martin wondering how this behaves on macOS for local dev - I don't think `nproc` is available OOTB

**Comment by aidenkeating** [comment]
@david-martin Tried out your update, on mac seeing:

```
Using native os lib to determine num cpus
MASTER: numCPUs=8
App started at: Tue Jan 17 2017 15:06:19 GMT+0000 (GMT) on port: 8001
App started at: Tue Jan 17 2017 15:06:19 GMT+0000 (GMT) on port: 8001
App started at: Tue Jan 17 2017 15:06:19 GMT+0000 (GMT) on port: 8001
App started at: Tue Jan 17 2017 15:06:19 GMT+0000 (GMT) on port: 8001
App started at: Tue Jan 17 2017 15:06:19 GMT+0000 (GMT) on port: 8001
App started at: Tue Jan 17 2017 15:06:19 GMT+0000 (GMT) on port: 8001
App started at: Tue Jan 17 2017 15:06:19 GMT+0000 (GMT) on port: 8001
App started at: Tue Jan 17 2017 15:06:19 GMT+0000 (GMT) on port: 8001
```

**Comment by wtrocki** [comment]
@david-martin Awesome changes! This seems like good candidate for separate module that can be extended and added to any existing cloud app. WDYT? 

To verify that we would also need to kill one of the workers and check if new one is restarted. 
We may also issue stop signal and check if the master process is being killed.

**Comment by david-martin** [comment]
@jasonmadigan I've updated the PR to fall back to the nodejs `os` lib if the `nproc` cmd doesn't exist (see comment above from Aiden)

**Comment by david-martin** [comment]
@wtrocki I'm not really a fan of micro modules, so i'll leave the code inline as is. Its really not enough code in my opinion to warrant a module.
If you feel so inclined as to publish a module, then by all means go ahead and create a PR.

I'll do a test locally to ensure workers are restarted when killed, and stopping the master causes workers to stop.

**Comment by jasonmadigan** [comment]
@david-martin deadly, thanks Dave.

**Comment by david-martin** [comment]
Killing an individual worker spawns a replacement, as expected

```bash
sudo lsof -i :8001
COMMAND     PID    USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
fh-NO-APP 23017 dmartin   20u  IPv4 2699568      0t0  TCP *:vcom-tunnel (LISTEN)
[dmartin@rollins-tp helloworld-cloud-cluster]$ ps -aef | grep fh-NO-APP
dmartin  23017  9602  0 15:49 pts/4    00:00:00 fh-NO-APPNAME-DEFIN
dmartin  23027 23017  0 15:49 pts/4    00:00:01 fh-NO-APPNAME-DEFINED
dmartin  23032 23017  0 15:49 pts/4    00:00:01 fh-NO-APPNAME-DEFINED
dmartin  23037 23017  0 15:49 pts/4    00:00:00 fh-NO-APPNAME-DEFINED
dmartin  23042 23017  0 15:49 pts/4    00:00:00 fh-NO-APPNAME-DEFINED
dmartin  23047 23017  0 15:49 pts/4    00:00:01 fh-NO-APPNAME-DEFINED
dmartin  23052 23017  0 15:49 pts/4    00:00:01 fh-NO-APPNAME-DEFINED
dmartin  23057 23017  0 15:49 pts/4    00:00:00 fh-NO-APPNAME-DEFINED
dmartin  23058 23017  0 15:49 pts/4    00:00:01 fh-NO-APPNAME-DEFINED
dmartin  23325 22776  0 15:52 pts/5    00:00:00 grep --color=auto fh-NO-APP
[dmartin@rollins-tp helloworld-cloud-cluster]$ ps -aef | grep fh-NO-APP| wc -l
10

[dmartin@rollins-tp helloworld-cloud-cluster]$ kill -9 23058
[dmartin@rollins-tp helloworld-cloud-cluster]$ ps -aef | grep fh-NO-APP| wc -l
10
```

```
Worker: 23057 has died!! code=null signal=SIGKILL Respawning..
body-parser deprecated bodyParser: use individual json/urlencoded middlewares lib/hello.js:8:13
body-parser deprecated undefined extended: provide extended option node_modules/body-parser/index.js:105:29
App started at: Tue Jan 17 2017 15:52:52 GMT+0000 (GMT) on port: 8001
```

Killing the master will kill all workers
```bash
[dmartin@rollins-tp helloworld-cloud-cluster]$ ps -aef | grep fh-NO-APP
dmartin  23017  9602  0 15:49 pts/4    00:00:00 fh-NO-APPNAME-DEFIN
dmartin  23027 23017  0 15:49 pts/4    00:00:01 fh-NO-APPNAME-DEFINED
dmartin  23032 23017  0 15:49 pts/4    00:00:01 fh-NO-APPNAME-DEFINED
dmartin  23037 23017  0 15:49 pts/4    00:00:01 fh-NO-APPNAME-DEFINED
dmartin  23042 23017  0 15:49 pts/4    00:00:01 fh-NO-APPNAME-DEFINED
dmartin  23047 23017  0 15:49 pts/4    00:00:01 fh-NO-APPNAME-DEFINED
dmartin  23052 23017  0 15:49 pts/4    00:00:01 fh-NO-APPNAME-DEFINED
dmartin  23337 23017  2 15:52 pts/4    00:00:00 fh-NO-APPNAME-DEFINED
dmartin  23352 23017  8 15:52 pts/4    00:00:00 fh-NO-APPNAME-DEFINED
dmartin  23367 22776  0 15:52 pts/5    00:00:00 grep --color=auto fh-NO-APP

[dmartin@rollins-tp helloworld-cloud-cluster]$ kill -9 23017
[dmartin@rollins-tp helloworld-cloud-cluster]$ ps -aef | grep fh-NO-APP
dmartin  23419 22776  0 15:54 pts/5    00:00:00 grep --color=auto fh-NO-APP

```

```
App started at: Tue Jan 17 2017 15:52:52 GMT+0000 (GMT) on port: 8001
Killed
```

**Comment by david-martin** [comment]
Logs from cloud app when deployed to a 1 CPU Environment

```
Using nproc to determine num cpus
MASTER: numCPUs=1
amqp connected
App started at: Tue Jan 17 2017 15:58:14 GMT+0000 (UTC) on port: 8184
amqp connected
```

**Comment by david-martin** [comment]
Logs from cloud app when deployed to a 2 CPU Environment

```
Using nproc to determine num cpus
MASTER: numCPUs=2
amqp connected
App started at: Tue Jan 17 2017 17:41:28 GMT+0000 (UTC) on port: 8180
App started at: Tue Jan 17 2017 17:41:28 GMT+0000 (UTC) on port: 8180
amqp connected
amqp connected
```

**Pull request merged**
